---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "miniflux/miniflux:2.0.44"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
            - configMapRef:
                name: "app-sentinel"
            - secretRef:
                # we can't let kustomize handle this because this secret is
                # unknown to it because it's the result of unsealing the secret
                name: "miniflux-app-secret"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
